apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-ticker
  namespace: {{ .Release.Namespace }}
  labels:
    app: stock-ticker
spec:
  selector:
    matchLabels:
      app: stock-ticker
  template:
    metadata:
      labels:
        app: stock-ticker
      annotations:
        checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        checksum/secret-env: {{ include (print $.Template.BasePath "/secret-env.yaml") . | sha256sum }}
    spec:
      containers:
        - name: stock-ticker
          image: "{{ .Values.image.registry }}/{{ .Values.image.org }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: stock-ticker-secret-env
            - configMapRef:
                name: stock-ticker-configmap-env
          ports:
          - name: application
            containerPort: {{.Values.deployment.containerPort}}
            protocol: TCP
