apiVersion: v1
kind: Secret
metadata:
  name: stock-ticker-secret-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: stock-ticker
data:
  {{- range $key, $value := .Values.deployment.secretEnv }}
  {{ $key | quote }}: {{ $value | toString | b64enc | quote  }}
  {{- end }}
