apiVersion: v1
kind: Service
metadata:
  name: stock-ticker
  namespace: {{ .Release.Namespace }}
  labels:
    app: stock-ticker
spec:
  type: ClusterIP
  ports:
  - name: application
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: stock-ticker
